name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v4.0.3
        with:
          major_pattern : "major:"
          minor_pattern : "feat:"
        id: version

      - name: Login DockerHub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USER }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKER_PASSWORD}}
        run : |
          echo "Loing starting..."
          docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
      - name: Build the Docker image
        NEW_VERSION: ${{ steps.version.outputs.version }}
        run:  |
          docker build  -t alemanadigital/docker-graphql:$NEW_VERSION .
          docker build  -t alemanadigital/docker-graphql:latest .

      - name: Push the Docker image to the repository
        run: |
         docker push alemanadigital/docker-graphql:$NEW_VERSION
         docker push alemanadigital/docker-graphql:latest



    # - uses: actions/checkout@v3
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
